// <auto-generated />
namespace Crud_operation_Empty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ProductAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202501251325265_ProductAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
